// ============================================================
//  ENEMIES.JS
//  Enemy definitions and categories
// ============================================================

export const ENEMY_DEFS = {
  // ── Base Enemies ─
  normal: {
    id: 'normal',
    label: 'Goblin',
    hp: 80,
    speed: 80,
    reward: 15,
    size: 14,
    color: '#EF5350',
    damage: 1,
    world: 'forest',
  },
  fast: {
    id: 'fast',
    label: 'Wolf',
    hp: 45,
    speed: 160,
    reward: 20,
    size: 11,
    color: '#AB47BC',
    damage: 1,
    world: 'forest',
  },
  tank: {
    id: 'tank',
    label: 'Treant',
    hp: 280,
    speed: 45,
    reward: 40,
    size: 20,
    color: '#78909C',
    damage: 3,
    world: 'forest',
  },
  healer: {
    id: 'healer',
    label: 'Fairy',
    hp: 60,
    speed: 55,
    reward: 25,
    size: 12,
    color: '#4CAF50',
    damage: 1,
    ability: 'heal',
    healAmount: 10,
    healRadius: 60,
    healInterval: 1.0,
    world: 'forest',
  },
  shielded: {
    id: 'shielded',
    label: 'Armored Guard',
    hp: 150,
    speed: 60,
    reward: 35,
    size: 16,
    color: '#90A4AE',
    damage: 2,
    ability: 'shield',
    shieldThreshold: 0.5,
    damageReduction: 0.5,
    world: 'forest',
  },
  boss: {
    id: 'boss',
    label: 'Forest Guardian',
    hp: 500,
    speed: 30,
    reward: 100,
    size: 28,
    color: '#D32F2F',
    damage: 5,
    isBoss: true,
    world: 'forest',
  },

  // ── NEW: Special Enemies for enhanced gameplay ─
  brute: {
    id: 'brute',
    label: 'Brute',
    hp: 250,
    speed: 45,
    reward: 30,
    size: 22,
    color: '#78716c',
    damage: 3,
    // Special: Immune to slow, poison; takes reduced damage
    immuneTo: ['slow', 'poison', 'freeze'],
    armor: 0.3,
    world: 'forest',
  },
  phase: {
    id: 'phase',
    label: 'Phase Runner',
    hp: 80,
    speed: 100,
    reward: 15,
    size: 14,
    color: '#8b5cf6',
    damage: 1,
    // Special: Briefly becomes invulnerable every 5 seconds
    ability: 'phase_shift',
    phaseDuration: 1.5,
    phaseCooldown: 5,
    world: 'desert',
  },
  phantom: {
    id: 'phantom',
    label: 'Phantom',
    hp: 50,
    speed: 120,
    reward: 20,
    size: 12,
    color: '#06b6d4',
    damage: 1,
    // Special: Teleports forward 20% of path every 10 seconds
    ability: 'teleport',
    teleportInterval: 10,
    teleportDistance: 0.2,
    world: 'ice',
  },
  medic: {
    id: 'medic',
    label: 'Combat Medic',
    hp: 80,
    speed: 70,
    reward: 25,
    size: 14,
    color: '#22c55e',
    damage: 1,
    // Special: Heals nearby enemies
    ability: 'heal_aura',
    healRadius: 80,
    healRate: 15,
    healInterval: 1.0,
    world: 'ice',
  },
  necromancer: {
    id: 'necromancer',
    label: 'Necromancer',
    hp: 150,
    speed: 50,
    reward: 40,
    size: 16,
    color: '#a855f7',
    damage: 2,
    // Special: Spawns weak minions periodically
    ability: 'summon',
    summonCount: 3,
    summonInterval: 8,
    summonType: 'skeleton',
    world: 'volcanic',
  },
  juggernaut: {
    id: 'juggernaut',
    label: 'Juggernaut',
    hp: 500,
    speed: 35,
    reward: 80,
    size: 28,
    color: '#dc2626',
    damage: 5,
    // Special: Has shield that regenerates
    shieldMax: 200,
    shieldRegen: 10,
    shieldRegenDelay: 3,
    isBoss: false,
    world: 'volcanic',
  },
  swarmQueen: {
    id: 'swarm',
    label: 'Swarm Queen',
    hp: 100,
    speed: 110,
    reward: 25,
    size: 15,
    color: '#f97316',
    damage: 2,
    // Special: Spawns mini-swarm on death
    spawnOnDeath: 5,
    spawnType: 'swarmling',
    spawnRadius: 50,
    world: 'forest',
  },
  swarmling: {
    id: 'swarmling',
    label: 'Swarmling',
    hp: 28,
    speed: 125,
    reward: 8,
    size: 9,
    color: '#fbbf24',
    damage: 1,
    world: 'forest',
  },
  stalker: {
    id: 'stalker',
    label: 'Stalker',
    hp: 60,
    speed: 90,
    reward: 18,
    size: 13,
    color: '#1f2937',
    damage: 1,
    // Special: Invisible until within 100px of tower
    invisible: true,
    revealDistance: 100,
    world: 'cosmic',
  },

  // ── Desert Enemies ─
  scorpion: {
    id: 'scorpion',
    label: 'Sand Scorpion',
    hp: 70,
    speed: 130,
    reward: 18,
    size: 13,
    color: '#D4A574',
    damage: 1,
    world: 'desert',
  },
  sandWorm: {
    id: 'sandWorm',
    label: 'Sand Worm',
    hp: 200,
    speed: 70,
    reward: 35,
    size: 18,
    color: '#BCAAA4',
    damage: 2,
    world: 'desert',
  },
  mummy: {
    id: 'mummy',
    label: 'Mummy',
    hp: 120,
    speed: 60,
    reward: 28,
    size: 15,
    color: '#8D6E63',
    damage: 2,
    world: 'desert',
  },
  pharaoh: {
    id: 'pharaoh',
    label: 'Pharaoh',
    hp: 800,
    speed: 35,
    reward: 200,
    size: 26,
    color: '#FFD54F',
    damage: 4,
    isBoss: true,
    world: 'desert',
  },
  scorpionKing: {
    id: 'scorpionKing',
    label: 'Scorpion King',
    hp: 1000,
    speed: 40,
    reward: 250,
    size: 30,
    color: '#8D1F00',
    damage: 5,
    isBoss: true,
    world: 'desert',
  },

  // ── Ice Enemies ─
  frostElemental: {
    id: 'frostElemental',
    label: 'Frost Elemental',
    hp: 90,
    speed: 90,
    reward: 22,
    size: 14,
    color: '#81D4FA',
    damage: 1,
    world: 'ice',
  },
  iceGolem: {
    id: 'iceGolem',
    label: 'Ice Golem',
    hp: 300,
    speed: 40,
    reward: 50,
    size: 22,
    color: '#B3E5FC',
    damage: 3,
    world: 'ice',
  },
  snowWolf: {
    id: 'snowWolf',
    label: 'Snow Wolf',
    hp: 55,
    speed: 170,
    reward: 20,
    size: 12,
    color: '#ECEFF1',
    damage: 1,
    world: 'ice',
  },
  frostMage: {
    id: 'frostMage',
    label: 'Frost Mage',
    hp: 80,
    speed: 50,
    reward: 30,
    size: 13,
    color: '#4FC3F7',
    damage: 2,
    world: 'ice',
  },
  crystalSpider: {
    id: 'crystalSpider',
    label: 'Crystal Spider',
    hp: 100,
    speed: 120,
    reward: 25,
    size: 14,
    color: '#E1BEE7',
    damage: 1,
    world: 'ice',
  },
  iceKing: {
    id: 'iceKing',
    label: 'Ice King',
    hp: 1200,
    speed: 30,
    reward: 300,
    size: 28,
    color: '#0288D1',
    damage: 5,
    isBoss: true,
    world: 'ice',
  },
  iceQueen: {
    id: 'iceQueen',
    label: 'Ice Queen',
    hp: 1000,
    speed: 35,
    reward: 280,
    size: 26,
    color: '#7B1FA2',
    damage: 4,
    isBoss: true,
    world: 'ice',
  },
  iceDragon: {
    id: 'iceDragon',
    label: 'Ice Dragon',
    hp: 2000,
    speed: 45,
    reward: 500,
    size: 32,
    color: '#00BCD4',
    damage: 6,
    isBoss: true,
    world: 'ice',
  },

  // ── Volcanic Enemies ─
  lavaElemental: {
    id: 'lavaElemental',
    label: 'Lava Elemental',
    hp: 150,
    speed: 75,
    reward: 30,
    size: 16,
    color: '#FF5722',
    damage: 2,
    world: 'volcanic',
  },
  fireImp: {
    id: 'fireImp',
    label: 'Fire Imp',
    hp: 50,
    speed: 180,
    reward: 18,
    size: 11,
    color: '#FFAB91',
    damage: 1,
    world: 'volcanic',
  },
  ashDrake: {
    id: 'ashDrake',
    label: 'Ash Drake',
    hp: 250,
    speed: 100,
    reward: 45,
    size: 20,
    color: '#5D4037',
    damage: 3,
    world: 'volcanic',
  },
  lavaGolem: {
    id: 'lavaGolemEnemy',
    label: 'Lava Golem',
    hp: 400,
    speed: 35,
    reward: 60,
    size: 24,
    color: '#BF360C',
    damage: 4,
    world: 'volcanic',
  },
  fireDemon: {
    id: 'fireDemon',
    label: 'Fire Demon',
    hp: 180,
    speed: 85,
    reward: 40,
    size: 17,
    color: '#D84315',
    damage: 3,
    world: 'volcanic',
  },
  fireElementalLord: {
    id: 'fireElementalLord',
    label: 'Fire Elemental Lord',
    hp: 2500,
    speed: 40,
    reward: 600,
    size: 30,
    color: '#FF3D00',
    damage: 6,
    isBoss: true,
    world: 'volcanic',
  },
  pitLord: {
    id: 'pitLord',
    label: 'Pit Lord',
    hp: 1800,
    speed: 45,
    reward: 450,
    size: 28,
    color: '#4E342E',
    damage: 5,
    isBoss: true,
    world: 'volcanic',
  },
  volcanoGod: {
    id: 'volcanoGod',
    label: 'Volcano God',
    hp: 3500,
    speed: 35,
    reward: 800,
    size: 34,
    color: '#BF360C',
    damage: 8,
    isBoss: true,
    world: 'volcanic',
  },
  demonKing: {
    id: 'demonKing',
    label: 'Demon King',
    hp: 4000,
    speed: 40,
    reward: 1000,
    size: 36,
    color: '#212121',
    damage: 10,
    isBoss: true,
    world: 'volcanic',
  },

  // ── Cosmic Enemies ─
  cosmicDrifter: {
    id: 'cosmicDrifter',
    label: 'Cosmic Drifter',
    hp: 100,
    speed: 130,
    reward: 25,
    size: 13,
    color: '#7C4DFF',
    damage: 1,
    world: 'cosmic',
  },
  voidSpawn: {
    id: 'voidSpawn',
    label: 'Void Spawn',
    hp: 60,
    speed: 200,
    reward: 22,
    size: 10,
    color: '#311B92',
    damage: 1,
    world: 'cosmic',
  },
  starSentinel: {
    id: 'starSentinel',
    label: 'Star Sentinel',
    hp: 300,
    speed: 70,
    reward: 55,
    size: 18,
    color: '#FFD600',
    damage: 3,
    world: 'cosmic',
  },
  darkMatter: {
    id: 'darkMatter',
    label: 'Dark Matter',
    hp: 400,
    speed: 50,
    reward: 70,
    size: 20,
    color: '#1A1A2E',
    damage: 4,
    world: 'cosmic',
  },
  voidLord: {
    id: 'voidLord',
    label: 'Void Lord',
    hp: 1500,
    speed: 55,
    reward: 350,
    size: 26,
    color: '#4A148C',
    damage: 5,
    isBoss: true,
    world: 'cosmic',
  },
  voidBehemoth: {
    id: 'voidBehemoth',
    label: 'Void Behemoth',
    hp: 3000,
    speed: 40,
    reward: 700,
    size: 32,
    color: '#0D0221',
    damage: 7,
    isBoss: true,
    world: 'cosmic',
  },
  cosmicGuardian: {
    id: 'cosmicGuardian',
    label: 'Cosmic Guardian',
    hp: 4000,
    speed: 45,
    reward: 900,
    size: 30,
    color: '#651FFF',
    damage: 6,
    isBoss: true,
    world: 'cosmic',
  },
  dimensionRift: {
    id: 'dimensionRift',
    label: 'Dimension Rift',
    hp: 5000,
    speed: 35,
    reward: 1200,
    size: 36,
    color: '#311B92',
    damage: 8,
    isBoss: true,
    world: 'cosmic',
  },
  cosmicDestroyer: {
    id: 'cosmicDestroyer',
    label: 'Cosmic Destroyer',
    hp: 8000,
    speed: 50,
    reward: 2500,
    size: 40,
    color: '#000000',
    damage: 15,
    isBoss: true,
    world: 'cosmic',
  },
};

// Get enemy definition by ID
export function getEnemyDef(enemyId) {
  return ENEMY_DEFS[enemyId] || null;
}

// ── Wave Definitions (Legacy - for compatibility) ────────────
