// ============================================================
//  TOWERS.JS
//  Tower definitions and categories
// ============================================================

export const TOWER_DEFS = {
  // ── Basic Towers (available from start) ─
  basic: {
    id: 'basic',
    label: 'Basic Tower',
    cost: 75,
    color: '#4FC3F7',
    accentColor: '#0288D1',
    bulletColor: '#E1F5FE',
    description: 'Single-target. Reliable.',
    splash: false,
    world: 'forest',
    levels: [
      { damage: 20, range: 120, fireRate: 1.2, bulletSpeed: 280, splash: 0, splashRadius: 0 },
      { damage: 38, range: 140, fireRate: 1.6, bulletSpeed: 320, splash: 0, splashRadius: 0 },
      { damage: 60, range: 160, fireRate: 2.0, bulletSpeed: 360, splash: 0, splashRadius: 0 },
      {
        damage: 90,
        range: 180,
        fireRate: 2.5,
        projectileSpeed: 400,
        splash: false,
        splashRadius: 0,
      },
    ],
    upgradeCost: [100, 150, 200],
    // ── NEW: Branching Upgrade System ─
    branches: {
      // Path A: Damage focus
      damage: {
        name: 'Sharp Arrows',
        description: 'Increase raw damage output',
        icon: '⚔️',
        tiers: [
          { level: 1, cost: 50, stats: { damage: +10 }, description: '+10 damage' },
          { level: 2, cost: 100, stats: { damage: +20 }, description: '+20 damage' },
          {
            level: 3,
            cost: 200,
            stats: { damage: +30, critChance: 10 },
            description: '+30 damage, 10% crit',
          },
          { level: 4, cost: 400, stats: { critDamage: 50 }, description: '+50% crit damage' },
        ],
        prerequisites: [],
      },
      // Path B: Speed focus
      speed: {
        name: 'Rapid Fire',
        description: 'Increase attack speed',
        icon: '⚡',
        tiers: [
          { level: 1, cost: 50, stats: { fireRate: 1.2 }, description: '+20% fire rate' },
          { level: 2, cost: 100, stats: { fireRate: 1.4 }, description: '+40% fire rate' },
          { level: 3, cost: 200, stats: { fireRate: 1.6 }, description: '+60% fire rate' },
          { level: 4, cost: 400, stats: { fireRate: 2.0 }, description: 'Double fire rate' },
        ],
        prerequisites: [],
      },
      // Path C: Range/Special
      range: {
        name: 'Eagle Eye',
        description: 'Extend range and reveal hidden',
        icon: '👁️',
        tiers: [
          { level: 1, cost: 50, stats: { range: 1.2 }, description: '+20% range' },
          { level: 2, cost: 100, stats: { range: 1.4 }, description: '+40% range' },
          {
            level: 3,
            cost: 200,
            stats: { range: 1.5, seeInvisible: true },
            description: '+50% range, reveal hidden',
          },
          {
            level: 4,
            cost: 400,
            stats: { aura: 'range', auraBonus: 15 },
            description: '+15% range aura to nearby',
          },
        ],
        prerequisites: [],
      },
    },
    // Branch unlocks at level 2
    branchUnlockLevel: 2,
  },
  splash: {
    id: 'splash',
    label: 'Splash Tower',
    cost: 125,
    color: '#FFB74D',
    accentColor: '#E65100',
    bulletColor: '#FFCC02',
    description: 'AOE damage. Slow fire rate.',
    splash: true,
    world: 'forest',
    levels: [
      { damage: 15, range: 100, fireRate: 0.6, bulletSpeed: 200, splash: true, splashRadius: 55 },
      { damage: 28, range: 120, fireRate: 0.8, bulletSpeed: 220, splash: true, splashRadius: 70 },
      { damage: 45, range: 140, fireRate: 1.0, bulletSpeed: 240, splash: true, splashRadius: 85 },
      { damage: 65, range: 160, fireRate: 1.3, bulletSpeed: 260, splash: true, splashRadius: 100 },
    ],
    upgradeCost: [150, 200, 250],
    // ── Branching Upgrade System ─
    branches: {
      // Path A: Area focus
      area: {
        name: 'Blast Radius',
        description: 'Increase splash damage area',
        icon: '💥',
        tiers: [
          { level: 1, cost: 75, stats: { splashRadius: 1.2 }, description: '+20% splash radius' },
          { level: 2, cost: 150, stats: { splashRadius: 1.4 }, description: '+40% splash radius' },
          {
            level: 3,
            cost: 300,
            stats: { splashRadius: 1.6, chainLightning: true },
            description: '+60% splash, chain lightning',
          },
          {
            level: 4,
            cost: 500,
            stats: { splashRadius: 2.0 },
            description: 'Double splash radius',
          },
        ],
        prerequisites: [],
      },
      // Path B: Damage focus
      power: {
        name: 'Explosive Power',
        description: 'Increase damage output',
        icon: '🔥',
        tiers: [
          { level: 1, cost: 75, stats: { damage: 1.3 }, description: '+30% damage' },
          { level: 2, cost: 150, stats: { damage: 1.5 }, description: '+50% damage' },
          { level: 3, cost: 300, stats: { damage: 1.8 }, description: '+80% damage' },
          {
            level: 4,
            cost: 500,
            stats: { damage: 2.2, armorPierce: true },
            description: '+120% damage, armor piercing',
          },
        ],
        prerequisites: [],
      },
      // Path C: Fire rate
      rapid: {
        name: 'Quick Load',
        description: 'Increase fire rate',
        icon: '🚀',
        tiers: [
          { level: 1, cost: 75, stats: { fireRate: 1.25 }, description: '+25% fire rate' },
          { level: 2, cost: 150, stats: { fireRate: 1.5 }, description: '+50% fire rate' },
          { level: 3, cost: 300, stats: { fireRate: 1.75 }, description: '+75% fire rate' },
          { level: 4, cost: 500, stats: { fireRate: 2.0 }, description: 'Double fire rate' },
        ],
        prerequisites: [],
      },
    },
    branchUnlockLevel: 2,
  },
  ice: {
    id: 'ice',
    label: 'Ice Tower',
    cost: 100,
    color: '#81D4FA',
    accentColor: '#0277BD',
    bulletColor: '#B3E5FC',
    description: 'Slows enemies by 40% for 2 seconds.',
    splash: false,
    slowEffect: { amount: 0.4, duration: 2.0 },
    world: 'forest',
    levels: [
      {
        damage: 10,
        range: 110,
        fireRate: 1.0,
        bulletSpeed: 250,
        slowAmount: 0.3,
        slowDuration: 1.5,
      },
      {
        damage: 18,
        range: 130,
        fireRate: 1.3,
        bulletSpeed: 280,
        slowAmount: 0.4,
        slowDuration: 2.0,
      },
      {
        damage: 28,
        range: 150,
        fireRate: 1.6,
        bulletSpeed: 310,
        slowAmount: 0.5,
        slowDuration: 2.5,
      },
      {
        damage: 40,
        range: 170,
        fireRate: 2.0,
        bulletSpeed: 340,
        slowAmount: 0.6,
        slowDuration: 3.0,
      },
    ],
    upgradeCost: [80, 130, 180],
  },
  sniper: {
    id: 'sniper',
    label: 'Sniper Tower',
    cost: 150,
    color: '#CE93D8',
    accentColor: '#7B1FA2',
    bulletColor: '#E1BEE7',
    description: 'Long range, high damage. Cannot be dodged.',
    splash: false,
    world: 'forest',
    levels: [
      { damage: 80, range: 200, fireRate: 0.5, bulletSpeed: 500, splash: false, splashRadius: 0 },
      { damage: 120, range: 230, fireRate: 0.6, bulletSpeed: 550, splash: false, splashRadius: 0 },
      { damage: 180, range: 260, fireRate: 0.7, bulletSpeed: 600, splash: false, splashRadius: 0 },
      { damage: 250, range: 300, fireRate: 0.8, bulletSpeed: 650, splash: false, splashRadius: 0 },
    ],
    upgradeCost: [120, 180, 250],
    // ── Branching Upgrade System ─
    branches: {
      // Path A: Extreme range
      longRange: {
        name: 'Hawkeye',
        description: 'Extreme range for picking off enemies',
        icon: '🎯',
        tiers: [
          { level: 1, cost: 100, stats: { range: 1.25 }, description: '+25% range' },
          { level: 2, cost: 200, stats: { range: 1.5 }, description: '+50% range' },
          {
            level: 3,
            cost: 350,
            stats: { range: 1.75, pierce: 2 },
            description: '+75% range, pierce 2',
          },
          {
            level: 4,
            cost: 600,
            stats: { range: 2.0, pierce: 3 },
            description: 'Double range, pierce 3',
          },
        ],
        prerequisites: [],
      },
      // Path B: Critical hits
      crit: {
        name: 'Deadly Aim',
        description: 'Chance for massive critical damage',
        icon: '💀',
        tiers: [
          { level: 1, cost: 100, stats: { critChance: 15 }, description: '+15% crit chance' },
          {
            level: 2,
            cost: 200,
            stats: { critChance: 25, critDamage: 50 },
            description: '+25% crit, +50% damage',
          },
          {
            level: 3,
            cost: 350,
            stats: { critChance: 35, critDamage: 100 },
            description: '+35% crit, +100% damage',
          },
          {
            level: 4,
            cost: 600,
            stats: { critChance: 50, critDamage: 150, oneShotWeak: true },
            description: '50% crit, instakill weak',
          },
        ],
        prerequisites: [],
      },
      // Path C: Armor piercing
      pierce: {
        name: 'Armor Breaker',
        description: 'Bypass enemy armor',
        icon: '🛡️',
        tiers: [
          { level: 1, cost: 100, stats: { armorPierce: 30 }, description: '30% armor pierce' },
          { level: 2, cost: 200, stats: { armorPierce: 50 }, description: '50% armor pierce' },
          {
            level: 3,
            cost: 350,
            stats: { armorPierce: 70, ignoreShield: true },
            description: '70% armor pierce, ignore shield',
          },
          {
            level: 4,
            cost: 600,
            stats: { armorPierce: 100, trueDamage: true },
            description: '100% armor pierce, true damage',
          },
        ],
        prerequisites: [],
      },
    },
    branchUnlockLevel: 2,
  },
  poison: {
    id: 'poison',
    label: 'Poison Tower',
    cost: 115,
    color: '#4ade80',
    accentColor: '#166534',
    bulletColor: '#86efac',
    description: 'Applies poison damage over time.',
    splash: false,
    world: 'forest',
    levels: [
      {
        damage: 8,
        range: 115,
        fireRate: 0.95,
        bulletSpeed: 260,
        poisonDamage: 6,
        poisonDuration: 3.0,
      },
      {
        damage: 12,
        range: 135,
        fireRate: 1.15,
        bulletSpeed: 290,
        poisonDamage: 8,
        poisonDuration: 3.5,
      },
      {
        damage: 18,
        range: 155,
        fireRate: 1.35,
        bulletSpeed: 320,
        poisonDamage: 11,
        poisonDuration: 4.0,
      },
      {
        damage: 26,
        range: 175,
        fireRate: 1.6,
        bulletSpeed: 350,
        poisonDamage: 15,
        poisonDuration: 4.5,
      },
    ],
    upgradeCost: [90, 140, 210],
  },

  // ── Forest World Towers ─
  archer: {
    id: 'archer',
    label: 'Archer Tower',
    cost: 90,
    color: '#8B4513',
    accentColor: '#D2691E',
    bulletColor: '#DEB887',
    description: 'Rapid-fire arrows. High attack speed.',
    splash: false,
    world: 'forest',
    levels: [
      { damage: 12, range: 130, fireRate: 2.5, bulletSpeed: 350 },
      { damage: 20, range: 150, fireRate: 3.0, bulletSpeed: 380 },
      { damage: 30, range: 170, fireRate: 3.5, bulletSpeed: 410 },
      { damage: 45, range: 190, fireRate: 4.0, bulletSpeed: 450 },
    ],
    upgradeCost: [80, 120, 170],
  },
  trapper: {
    id: 'trapper',
    label: 'Trapper Tower',
    cost: 110,
    color: '#228B22',
    accentColor: '#006400',
    bulletColor: '#90EE90',
    description: 'Roots enemies in place. Immobilizes.',
    splash: false,
    world: 'forest',
    levels: [
      {
        damage: 8,
        range: 100,
        fireRate: 0.8,
        bulletSpeed: 200,
        slowAmount: 1.0,
        slowDuration: 2.0,
      },
      {
        damage: 14,
        range: 120,
        fireRate: 1.0,
        bulletSpeed: 230,
        slowAmount: 1.0,
        slowDuration: 2.5,
      },
      {
        damage: 22,
        range: 140,
        fireRate: 1.2,
        bulletSpeed: 260,
        slowAmount: 1.0,
        slowDuration: 3.0,
      },
      {
        damage: 32,
        range: 160,
        fireRate: 1.5,
        bulletSpeed: 290,
        slowAmount: 1.0,
        slowDuration: 3.5,
      },
    ],
    upgradeCost: [100, 150, 200],
  },
  sentinel: {
    id: 'sentinel',
    label: 'Sentinel Tower',
    cost: 175,
    color: '#2E8B57',
    accentColor: '#006400',
    bulletColor: '#ADFF2F',
    description: 'Exceptional range. Pierces multiple enemies.',
    splash: false,
    piercing: true,
    world: 'forest',
    levels: [
      { damage: 25, range: 250, fireRate: 0.6, bulletSpeed: 450, pierceCount: 3 },
      { damage: 40, range: 280, fireRate: 0.7, bulletSpeed: 500, pierceCount: 4 },
      { damage: 60, range: 310, fireRate: 0.8, bulletSpeed: 550, pierceCount: 5 },
      { damage: 85, range: 350, fireRate: 0.9, bulletSpeed: 600, pierceCount: 6 },
    ],
    upgradeCost: [150, 220, 300],
  },

  // ── Desert World Towers ─
  flamethrower: {
    id: 'flamethrower',
    label: 'Flamethrower',
    cost: 140,
    color: '#FF4500',
    accentColor: '#8B0000',
    bulletColor: '#FFA500',
    description: 'Continuous fire. Burns enemies over time.',
    splash: true,
    world: 'desert',
    burnEffect: { damage: 5, duration: 2.0 },
    levels: [
      {
        damage: 12,
        range: 90,
        fireRate: 3.0,
        bulletSpeed: 180,
        splashRadius: 45,
        burnDamage: 4,
        burnDuration: 1.5,
      },
      {
        damage: 20,
        range: 110,
        fireRate: 3.5,
        bulletSpeed: 200,
        splashRadius: 55,
        burnDamage: 6,
        burnDuration: 2.0,
      },
      {
        damage: 30,
        range: 130,
        fireRate: 4.0,
        bulletSpeed: 220,
        splashRadius: 65,
        burnDamage: 8,
        burnDuration: 2.5,
      },
      {
        damage: 45,
        range: 150,
        fireRate: 4.5,
        bulletSpeed: 240,
        splashRadius: 75,
        burnDamage: 10,
        burnDuration: 3.0,
      },
    ],
    upgradeCost: [130, 190, 260],
  },
  sandweaver: {
    id: 'sandweaver',
    label: 'Sandweaver',
    cost: 120,
    color: '#DAA520',
    accentColor: '#B8860B',
    bulletColor: '#F0E68C',
    description: 'Webs enemies. Extreme slow with moderate damage.',
    splash: false,
    world: 'desert',
    levels: [
      {
        damage: 10,
        range: 110,
        fireRate: 0.7,
        bulletSpeed: 220,
        slowAmount: 0.7,
        slowDuration: 3.0,
      },
      {
        damage: 18,
        range: 130,
        fireRate: 0.9,
        bulletSpeed: 250,
        slowAmount: 0.75,
        slowDuration: 3.5,
      },
      {
        damage: 28,
        range: 150,
        fireRate: 1.1,
        bulletSpeed: 280,
        slowAmount: 0.8,
        slowDuration: 4.0,
      },
      {
        damage: 40,
        range: 170,
        fireRate: 1.3,
        bulletSpeed: 310,
        slowAmount: 0.85,
        slowDuration: 4.5,
      },
    ],
    upgradeCost: [110, 160, 220],
  },
  duneCrawler: {
    id: 'duneCrawler',
    label: 'Dune Crawler',
    cost: 160,
    color: '#CD853F',
    accentColor: '#8B4513',
    bulletColor: '#D2691E',
    description: 'Fast attack speed. Chains to nearby enemies.',
    splash: false,
    chainLightning: true,
    world: 'desert',
    levels: [
      { damage: 15, range: 100, fireRate: 2.0, bulletSpeed: 400, chainCount: 2, chainRange: 60 },
      { damage: 25, range: 120, fireRate: 2.5, bulletSpeed: 440, chainCount: 3, chainRange: 70 },
      { damage: 38, range: 140, fireRate: 3.0, bulletSpeed: 480, chainCount: 4, chainRange: 80 },
      { damage: 55, range: 160, fireRate: 3.5, bulletSpeed: 520, chainCount: 5, chainRange: 90 },
    ],
    upgradeCost: [140, 200, 280],
  },

  // ── Ice World Towers ─
  frostBolt: {
    id: 'frostBolt',
    label: 'Frost Bolt',
    cost: 95,
    color: '#00BCD4',
    accentColor: '#00838F',
    bulletColor: '#E0F7FA',
    description: 'Heavy slow effect. Moderate damage.',
    splash: false,
    world: 'ice',
    levels: [
      {
        damage: 15,
        range: 120,
        fireRate: 1.2,
        bulletSpeed: 300,
        slowAmount: 0.5,
        slowDuration: 2.5,
      },
      {
        damage: 25,
        range: 140,
        fireRate: 1.5,
        bulletSpeed: 330,
        slowAmount: 0.55,
        slowDuration: 3.0,
      },
      {
        damage: 38,
        range: 160,
        fireRate: 1.8,
        bulletSpeed: 360,
        slowAmount: 0.6,
        slowDuration: 3.5,
      },
      {
        damage: 55,
        range: 180,
        fireRate: 2.2,
        bulletSpeed: 390,
        slowAmount: 0.65,
        slowDuration: 4.0,
      },
    ],
    upgradeCost: [90, 140, 190],
  },
  blizzard: {
    id: 'blizzard',
    label: 'Blizzard Tower',
    cost: 180,
    color: '#81D4FA',
    accentColor: '#0288D1',
    bulletColor: '#B3E5FC',
    description: 'Area slow effect. Freezes all enemies in range.',
    splash: true,
    areaSlow: true,
    world: 'ice',
    levels: [
      {
        damage: 8,
        range: 140,
        fireRate: 0.4,
        bulletSpeed: 150,
        areaSlowAmount: 0.3,
        areaSlowDuration: 1.0,
        splashRadius: 80,
      },
      {
        damage: 14,
        range: 160,
        fireRate: 0.5,
        bulletSpeed: 170,
        areaSlowAmount: 0.35,
        areaSlowDuration: 1.2,
        splashRadius: 95,
      },
      {
        damage: 22,
        range: 180,
        fireRate: 0.6,
        bulletSpeed: 190,
        areaSlowAmount: 0.4,
        areaSlowDuration: 1.5,
        splashRadius: 110,
      },
      {
        damage: 32,
        range: 200,
        fireRate: 0.7,
        bulletSpeed: 210,
        areaSlowAmount: 0.45,
        areaSlowDuration: 1.8,
        splashRadius: 125,
      },
    ],
    upgradeCost: [160, 230, 320],
  },
  crystalGuard: {
    id: 'crystalGuard',
    label: 'Crystal Guard',
    cost: 200,
    color: '#E1BEE7',
    accentColor: '#8E24AA',
    bulletColor: '#F3E5F5',
    description: 'Piercing attacks. Ignores enemy armor.',
    splash: false,
    piercing: true,
    armorPiercing: true,
    world: 'ice',
    levels: [
      {
        damage: 45,
        range: 180,
        fireRate: 0.7,
        bulletSpeed: 500,
        pierceCount: 4,
        armorPenetration: 0.5,
      },
      {
        damage: 70,
        range: 200,
        fireRate: 0.85,
        bulletSpeed: 550,
        pierceCount: 5,
        armorPenetration: 0.6,
      },
      {
        damage: 100,
        range: 220,
        fireRate: 1.0,
        bulletSpeed: 600,
        pierceCount: 6,
        armorPenetration: 0.7,
      },
      {
        damage: 140,
        range: 250,
        fireRate: 1.2,
        bulletSpeed: 650,
        pierceCount: 8,
        armorPenetration: 0.8,
      },
    ],
    upgradeCost: [180, 260, 350],
  },

  // ── Volcanic World Towers ─
  magmaCannon: {
    id: 'magmaCannon',
    label: 'Magma Cannon',
    cost: 165,
    color: '#FF5722',
    accentColor: '#BF360C',
    bulletColor: '#FFCCBC',
    description: 'Burning damage. Applies persistent burn.',
    splash: true,
    world: 'volcanic',
    burnEffect: { damage: 8, duration: 3.0 },
    levels: [
      {
        damage: 25,
        range: 130,
        fireRate: 0.8,
        bulletSpeed: 280,
        splashRadius: 60,
        burnDamage: 6,
        burnDuration: 2.5,
      },
      {
        damage: 40,
        range: 150,
        fireRate: 1.0,
        bulletSpeed: 310,
        splashRadius: 70,
        burnDamage: 9,
        burnDuration: 3.0,
      },
      {
        damage: 60,
        range: 170,
        fireRate: 1.2,
        bulletSpeed: 340,
        splashRadius: 80,
        burnDamage: 12,
        burnDuration: 3.5,
      },
      {
        damage: 85,
        range: 190,
        fireRate: 1.5,
        bulletSpeed: 370,
        splashRadius: 90,
        burnDamage: 15,
        burnDuration: 4.0,
      },
    ],
    upgradeCost: [150, 220, 300],
  },
  geyser: {
    id: 'geyser',
    label: 'Geyser Tower',
    cost: 145,
    color: '#00BCD4',
    accentColor: '#006064',
    bulletColor: '#E0F7FA',
    description: 'Knocks back enemies. Disrupts formations.',
    splash: true,
    knockback: true,
    world: 'volcanic',
    levels: [
      {
        damage: 12,
        range: 100,
        fireRate: 0.9,
        bulletSpeed: 250,
        knockbackForce: 40,
        splashRadius: 50,
      },
      {
        damage: 20,
        range: 120,
        fireRate: 1.1,
        bulletSpeed: 280,
        knockbackForce: 50,
        splashRadius: 60,
      },
      {
        damage: 30,
        range: 140,
        fireRate: 1.3,
        bulletSpeed: 310,
        knockbackForce: 60,
        splashRadius: 70,
      },
      {
        damage: 45,
        range: 160,
        fireRate: 1.6,
        bulletSpeed: 340,
        knockbackForce: 70,
        splashRadius: 80,
      },
    ],
    upgradeCost: [130, 190, 260],
  },
  lavaGolem: {
    id: 'lavaGolem',
    label: 'Lava Golem',
    cost: 250,
    color: '#D84315',
    accentColor: '#8D1F00',
    bulletColor: '#FFAB91',
    description: 'Massive damage. Slow but devastating.',
    splash: false,
    world: 'volcanic',
    levels: [
      { damage: 80, range: 110, fireRate: 0.4, bulletSpeed: 200 },
      { damage: 130, range: 130, fireRate: 0.5, bulletSpeed: 230 },
      { damage: 190, range: 150, fireRate: 0.6, bulletSpeed: 260 },
      { damage: 270, range: 170, fireRate: 0.7, bulletSpeed: 290 },
    ],
    upgradeCost: [220, 320, 450],
  },

  // ── Cosmic World Towers ─
  plasma: {
    id: 'plasma',
    label: 'Plasma Tower',
    cost: 185,
    color: '#7C4DFF',
    accentColor: '#651FFF',
    bulletColor: '#B388FF',
    description: 'Chains between enemies. Hits multiple targets.',
    chainLightning: true,
    world: 'cosmic',
    levels: [
      { damage: 20, range: 140, fireRate: 1.5, bulletSpeed: 450, chainCount: 3, chainRange: 70 },
      { damage: 32, range: 160, fireRate: 1.8, bulletSpeed: 500, chainCount: 4, chainRange: 80 },
      { damage: 48, range: 180, fireRate: 2.1, bulletSpeed: 550, chainCount: 5, chainRange: 90 },
      { damage: 68, range: 200, fireRate: 2.5, bulletSpeed: 600, chainCount: 6, chainRange: 100 },
    ],
    upgradeCost: [170, 240, 330],
  },
  voidEye: {
    id: 'voidEye',
    label: 'Void Eye',
    cost: 220,
    color: '#311B92',
    accentColor: '#1A0072',
    bulletColor: '#D1C4E9',
    description: 'Teleports enemies. Pulls them toward the tower.',
    pullEffect: true,
    world: 'cosmic',
    levels: [
      { damage: 15, range: 150, fireRate: 0.8, bulletSpeed: 350, pullForce: 50 },
      { damage: 25, range: 170, fireRate: 1.0, bulletSpeed: 390, pullForce: 60 },
      { damage: 38, range: 190, fireRate: 1.2, bulletSpeed: 430, pullForce: 70 },
      { damage: 55, range: 210, fireRate: 1.5, bulletSpeed: 470, pullForce: 80 },
    ],
    upgradeCost: [200, 280, 390],
  },
  starForge: {
    id: 'starForge',
    label: 'Star Forge',
    cost: 350,
    color: '#FFD600',
    accentColor: '#FF8F00',
    bulletColor: '#FFECB3',
    description: 'Devastating boss killer. Massive single-target damage.',
    splash: false,
    bossKiller: true,
    world: 'cosmic',
    levels: [
      { damage: 150, range: 180, fireRate: 0.35, bulletSpeed: 600, bossMultiplier: 2.0 },
      { damage: 220, range: 200, fireRate: 0.45, bulletSpeed: 650, bossMultiplier: 2.5 },
      { damage: 320, range: 220, fireRate: 0.55, bulletSpeed: 700, bossMultiplier: 3.0 },
      { damage: 450, range: 250, fireRate: 0.65, bulletSpeed: 750, bossMultiplier: 3.5 },
    ],
    upgradeCost: [300, 420, 580],
  },

  // ── Support Towers (Buff System) ─
  speedBoost: {
    id: 'speedBoost',
    label: 'Speed Boost',
    cost: 100,
    color: '#00E676',
    accentColor: '#00C853',
    bulletColor: '#B9F6CA',
    description: '+20% attack speed to towers in range.',
    isSupport: true,
    buffType: 'speed',
    buffAmount: 0.2,
    buffRadius: 144, // 3 tiles
    levels: [
      { range: 144, buffAmount: 0.2 },
      { range: 168, buffAmount: 0.25 },
      { range: 192, buffAmount: 0.3 },
      { range: 216, buffAmount: 0.35 },
    ],
    upgradeCost: [80, 120, 170],
  },
  damageAmp: {
    id: 'damageAmp',
    label: 'Damage Amp',
    cost: 120,
    color: '#FF5252',
    accentColor: '#D50000',
    bulletColor: '#FF8A80',
    description: '+25% damage to towers in range.',
    isSupport: true,
    buffType: 'damage',
    buffAmount: 0.25,
    buffRadius: 144,
    levels: [
      { range: 144, buffAmount: 0.25 },
      { range: 168, buffAmount: 0.3 },
      { range: 192, buffAmount: 0.35 },
      { range: 216, buffAmount: 0.4 },
    ],
    upgradeCost: [100, 150, 210],
  },
  rangeExtend: {
    id: 'rangeExtend',
    label: 'Range Extend',
    cost: 90,
    color: '#448AFF',
    accentColor: '#2962FF',
    bulletColor: '#82B1FF',
    description: '+15% range to towers in range.',
    isSupport: true,
    buffType: 'range',
    buffAmount: 0.15,
    buffRadius: 144,
    levels: [
      { range: 144, buffAmount: 0.15 },
      { range: 168, buffAmount: 0.2 },
      { range: 192, buffAmount: 0.25 },
      { range: 216, buffAmount: 0.3 },
    ],
    upgradeCost: [70, 110, 150],
  },
  critChance: {
    id: 'critChance',
    label: 'Crit Chance',
    cost: 140,
    color: '#E040FB',
    accentColor: '#AA00FF',
    bulletColor: '#EA80FC',
    description: '+15% critical hit chance to towers in range.',
    isSupport: true,
    buffType: 'crit',
    buffAmount: 0.15,
    buffRadius: 144,
    levels: [
      { range: 144, buffAmount: 0.15 },
      { range: 168, buffAmount: 0.2 },
      { range: 192, buffAmount: 0.25 },
      { range: 216, buffAmount: 0.3 },
    ],
    upgradeCost: [120, 180, 250],
  },
  healingAura: {
    id: 'healingAura',
    label: 'Healing Aura',
    cost: 150,
    color: '#69F0AE',
    accentColor: '#00C853',
    bulletColor: '#B9F6CA',
    description: 'Repairs nearby towers over time.',
    isSupport: true,
    buffType: 'heal',
    buffAmount: 5,
    buffRadius: 144,
    levels: [
      { range: 144, buffAmount: 5 },
      { range: 168, buffAmount: 8 },
      { range: 192, buffAmount: 12 },
      { range: 216, buffAmount: 15 },
    ],
    upgradeCost: [130, 190, 260],
  },
  energyShield: {
    id: 'energyShield',
    label: 'Energy Shield',
    cost: 200,
    color: '#40C4FF',
    accentColor: '#00B0FF',
    bulletColor: '#84FFFF',
    description: 'Temporary invulnerability for towers in range (triggered).',
    isSupport: true,
    buffType: 'shield',
    buffAmount: 1,
    buffRadius: 144,
    triggerRadius: 200,
    levels: [
      { range: 144, shieldDuration: 2.0, triggerRadius: 200 },
      { range: 168, shieldDuration: 2.5, triggerRadius: 220 },
      { range: 192, shieldDuration: 3.0, triggerRadius: 240 },
      { range: 216, shieldDuration: 3.5, triggerRadius: 260 },
    ],
    upgradeCost: [170, 250, 340],
  },
  synergyConnector: {
    id: 'synergyConnector',
    label: 'Synergy Connector',
    cost: 180,
    color: '#FFD740',
    accentColor: '#FFAB00',
    bulletColor: '#FFE57F',
    description: 'Shares cooldown between towers in range.',
    isSupport: true,
    buffType: 'synergy',
    buffAmount: 0.25,
    buffRadius: 168,
    levels: [
      { range: 168, synergyAmount: 0.25 },
      { range: 192, synergyAmount: 0.35 },
      { range: 216, synergyAmount: 0.45 },
      { range: 240, synergyAmount: 0.55 },
    ],
    upgradeCost: [150, 220, 300],
  },
  stun: {
    id: 'stun',
    label: 'Stun Tower',
    cost: 150,
    color: '#FFD700',
    accentColor: '#FFA000',
    bulletColor: '#FFF176',
    description: 'Stuns enemies briefly. Powerful crowd control.',
    splash: false,
    stunEffect: { duration: 0.5 },
    world: 'forest',
    levels: [
      {
        damage: 8,
        range: 110,
        fireRate: 0.6,
        bulletSpeed: 280,
        stunDuration: 0.5,
      },
      {
        damage: 12,
        range: 130,
        fireRate: 0.7,
        bulletSpeed: 310,
        stunDuration: 0.65,
      },
      {
        damage: 18,
        range: 150,
        fireRate: 0.85,
        bulletSpeed: 340,
        stunDuration: 0.8,
      },
      {
        damage: 26,
        range: 175,
        fireRate: 1.0,
        bulletSpeed: 370,
        stunDuration: 1.0,
      },
    ],
    upgradeCost: [120, 170, 240],
    // Branching upgrades
    branches: {
      duration: {
        name: 'Extended Stun',
        icon: '⏱️',
        tiers: [
          { level: 1, cost: 60, stats: { stunDuration: 0.15 }, description: '+0.15s stun' },
          { level: 2, cost: 120, stats: { stunDuration: 0.3 }, description: '+0.3s stun' },
          {
            level: 3,
            cost: 240,
            stats: { stunDuration: 0.5, aoeStun: true },
            description: '+0.5s, AoE stun',
          },
        ],
      },
      range: {
        name: 'Wider Reach',
        icon: '🎯',
        tiers: [
          { level: 1, cost: 60, stats: { range: 1.2 }, description: '+20% range' },
          { level: 2, cost: 120, stats: { range: 1.4 }, description: '+40% range' },
          {
            level: 3,
            cost: 240,
            stats: { range: 1.6, fireRate: 1.2 },
            description: '+60% range, +20% fire rate',
          },
        ],
      },
      damage: {
        name: 'Stun Damage',
        icon: '💥',
        tiers: [
          { level: 1, cost: 60, stats: { damage: 1.3 }, description: '+30% damage' },
          { level: 2, cost: 120, stats: { damage: 1.6 }, description: '+60% damage' },
          {
            level: 3,
            cost: 240,
            stats: { damage: 2.0, armorPierce: true },
            description: '+100% damage, armor piercing',
          },
        ],
      },
    },
    branchUnlockLevel: 2,
  },
};

// Get tower definition by ID
export function getTowerDef(towerId) {
  return TOWER_DEFS[towerId] || null;
}

// Get towers available for a specific world
export function getTowersForWorld(worldId, unlockedTowers = []) {
  const available = ['basic', 'splash', 'ice', 'sniper', 'poison'];

  // Add world-specific towers
  switch (worldId) {
    case 'forest':
      available.push('archer', 'trapper', 'sentinel');
      break;
    case 'desert':
      available.push('flamethrower', 'sandweaver', 'duneCrawler');
      break;
    case 'ice':
      available.push('frostBolt', 'blizzard', 'crystalGuard');
      break;
    case 'volcanic':
      available.push('magmaCannon', 'geyser', 'lavaGolem');
      break;
    case 'cosmic':
      available.push('plasma', 'voidEye', 'starForge');
      break;
    default:
      break;
  }

  // Add support towers (always available after unlocking)
  available.push(
    'speedBoost',
    'damageAmp',
    'rangeExtend',
    'critChance',
    'healingAura',
    'energyShield',
    'synergyConnector'
  );

  // Filter by unlocked towers if provided
  if (unlockedTowers.length > 0) {
    return available.filter((t) => unlockedTowers.includes(t));
  }

  return available;
}

// ── Enemy Definitions ────────────────────────────────────────
